// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btbifnkqslcleqyxptec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0Ymlmbmtxc2xjbGVxeXhwdGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODUwODMsImV4cCI6MjA2MTI2MTA4M30.1xEPLhd13XSrL6NUdPXwy8GOp-RCgkyT52iLuVPmXRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);