// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmqyobnckgzoysbpjuuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcXlvYm5ja2d6b3lzYnBqdXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTQ2MTksImV4cCI6MjA2MjQ3MDYxOX0.DxUfBsy7jQObQn-djI4KNqt_gUZCEc8E6eUfGxtwWiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);